Prefer using DeviceEvent over WindowEvent for mouse input handling
sotrh/learn-wgpu pull request #117
Opened 2020-10-31 07:29 UTC by jakeva

2020-10-31 22:12 UTC, sotrh requested changes
The README.md file for the camera tutorial will need to be updated as well.

2020-11-23 17:06 UTC, khuttun commented
Does DeviceEvent work in wasm32?

2020-11-24 06:42 UTC, sotrh commented
I'm not sure. That would probably be a good question for the folks at https://github.com/rust-windowing/winit

2020-11-25 23:53 UTC, sotrh commented
Closing this in favor of #127

2020-11-25 23:53 UTC, closed without merging