use winit::Window
sotrh/learn-wgpu pull request #147
Opened 2021-03-20 14:38 UTC by yutannihilation

or add `winit::` here

``` rust
async fn new(window: &Window) -> Self {
```

2021-03-21 22:34 UTC, sotrh requested changes

2021-03-21 22:34 UTC, sotrh commented on docs/beginner/tutorial2-swapchain/README.md
>  // main.rs
This should go above `use winit::Window;` as it's used to tell what file we're currently changing.

2021-03-21 23:21 UTC, yutannihilation commented
Thanks for catching. I also found I mistyped the module path, sorry...

2021-03-29 15:02 UTC, sotrh approved these changes

2021-03-29 15:02 UTC, merged