remove dereference operator (`*`) for `PhysicalSize`s
sotrh/learn-wgpu pull request #229
Opened 2021-09-12 12:25 UTC by leungyauming

WindowEvent::Resized carries a `PhysicalSize<u32>` type which implements the `Copy` trait,
WindowEvent::ScaleFactorChanged carries a `&mut PhysicalSize<u32>` type also implements the `Copy` trait.

In this case, there is no reason for dereferencing `PhysicalSize<u32>` and dereferencing `&mut PhysicalSize<u32>` twice.

2021-09-12 17:34 UTC, sotrh requested changes
Make the change in the code examples too. I can't except this change until then.

2021-09-16 07:51 UTC, leungyauming commented
Do I change all the examples?

2021-09-17 16:57 UTC, sotrh commented
Yes, I'd appreciate if you changed all the examples. You could probably do a find and replace to get it done.

2021-09-18 02:05 UTC, leungyauming commented
It actually is my mistake for removing the dereference operator, because I just found that your `State.resize` method takes a `PhysicalSize` instead of `&PhysicalSize`.

But I do think that your `State.resize` method should take a reference instead of a copy of `PhysicalSize`.
Because it is a tutorial, I'm afraid making such a big changes will bring confusion to many people and the code currently do work too, so I would like to know how do you think before I change the `State.resize` method.

If you decide not to make the changes, then I will close the PR, sorry for the mistake.

2021-09-19 19:03 UTC, sotrh commented
I opted to copy `PhysicalSize` instead of referencing it as the struct itself is fairly small (just two `u32`s currently). Adding an indirection via reference probably wouldn't add much benefit and potentially make the code slower (probably not an issue, but good to be aware of).

Given that you'd have to change the method definition as well it's probably best that we just close this issue.

2021-09-22 09:18 UTC, leungyauming commented
Understood.

2021-09-22 09:18 UTC, closed without merging