Typos, references to `main.rs` supposed to be to `lib.rs`, and readability changes
sotrh/learn-wgpu pull request #347
Opened 2022-04-17 16:53 UTC by dis-da-moe

- Fixed the typos and grammatical issues I could find, most are in the tutorial docs but one is in code
- Fixed some cases where the tutorial said to change or add code in `main.rs` when it should be `lib.rs`
- Added alt attribute to an image

2022-04-17 17:03 UTC, HeavyRain266 commented
Why did you completely removed indentions between curly braces in some places?

2022-04-17 18:11 UTC, dis-da-moe commented
> Why did you completely removed indentions between curly braces in some places?
Sorry that was unintentional I've pushed a commit that reverts that now.

2022-04-17 23:19 UTC, teoxoy commented
Could you fixup this as well?
https://github.com/sotrh/learn-wgpu/commit/4d33b048c219c7eb1136b13ef81d8a44b497ab5e#r71315264

I wanted to open a PR but noticed this one was already in the works.

2022-04-18 04:25 UTC, dis-da-moe commented
> Could you fixup this as well?

I was originally going to only do the tutorials I've read but I might as well go over the rest, I'll make a push soon for that.

2022-05-06 18:46 UTC, softmoth requested changes
This is fantastic. I hope it gets merged!

I've found a few minor items that I think might be improved.

2022-05-06 18:46 UTC, softmoth commented on docs/showcase/pong/README.md
> +I was messing around with separating state from the render code. It ended up similar to an entity-component system.
This is referring to an ECS. Use of that term is all over the map, but I think `Entity Component System model` would be the best way to refer to it here. "System" is a first-class element of the pattern here.

2022-05-06 20:41 UTC, dis-da-moe commented
Thanks for the suggestions I've added those now

2022-05-14 17:26 UTC, sotrh approved these changes

2022-05-14 18:44 UTC, merged